import {CHANNEL_TYPE, PLATFORM_TYPE} from '../platform/type';

export const channelEnabledByPlatform: Record<PLATFORM_TYPE, CHANNEL_TYPE[]> = {
  [PLATFORM_TYPE.GOLIKE]: [CHANNEL_TYPE.TIKTOK],
  [PLATFORM_TYPE.TDS]: [CHANNEL_TYPE.TIKTOK],
  [PLATFORM_TYPE.TTC]: [CHANNEL_TYPE.TIKTOK],
};
