import {CHANNEL_TYPE, PLATFORM_TYPE} from '../platform/type';

export const channelEnabledByPlatform: Record<PLATFORM_TYPE, CHANNEL_TYPE[]> = {
  [PLATFORM_TYPE.GOLIKE]: [CHANNEL_TYPE.TIKTOK],
  [PLATFORM_TYPE.TDS]: [
    CHANNEL_TYPE.TIKTOK,
    CHANNEL_TYPE.YOUTUBE,
    CHANNEL_TYPE.FACEBOOK,
    CHANNEL_TYPE.INSTAGRAM,
    CHANNEL_TYPE.SHOPEE,
  ],
  [PLATFORM_TYPE.TTC]: [],
};
